//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiaSeCode_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Code()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int MaCode { get; set; }
        public string TenMaCode { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDungCode { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotTai { get; set; }
        public string LinkTai { get; set; }
        public string NoiDungCaiDat { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> LuotDanhGia { get; set; }
        public string Token { get; set; }
        public Nullable<bool> Duyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
