//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiaSeCode_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTinTuc { get; set; }
        public string TenTinTuc { get; set; }
        public Nullable<System.DateTime> NgayDangTinTuc { get; set; }
        public string NoiDungTinTuc { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaTheLoaiTinTuc { get; set; }
        public string AnhTinTuc { get; set; }
        public Nullable<int> LuotXemTinTuc { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TheLoaiTinTuc TheLoaiTinTuc { get; set; }
    }
}
