//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiaSeCode_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraLoiBinhLuan
    {
        public int MaTraLoiBinhLuan { get; set; }
        public Nullable<System.DateTime> NgayTraLoiBinhLuan { get; set; }
        public Nullable<int> MaBinhLuan { get; set; }
        public string NoiDungTraLoiBinhLuan { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
    
        public virtual BinhLuan BinhLuan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
